apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tier-3-app-b-viewer
  namespace: ns-$i
spec:
  selector:
    matchLabels:
      app: tier-3-app-b
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/ns-$i/sa/tier-2-app-c
        - cluster.local/ns/ns-$i/sa/tier-2-app-d
        - cluster.local/ns/ns-$i/sa/waypoint
