apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tier-1-app-b-viewer
  namespace: ns-$i
spec:
  selector:
    matchLabels:
      app: tier-1-app-b
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/ns-$i/sa/vegeta2
        - cluster.local/ns/ns-$i/sa/waypoint
