apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tier-2-app-c-viewer
  namespace: ns-$i
spec:
  selector:
    matchLabels:
      app: tier-2-app-c
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/ns-$i/sa/tier-1-app-b
        - cluster.local/ns/ns-$i/sa/waypoint
