apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: tier-2-b
spec:
  endpointSelector:
    matchLabels:
      app: tier-2-app-b
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: tier-1-app-a
    toPorts:
    - ports:
      - port: '8080'
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/"
