apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: tier-3-app-a
  labels:
    app: tier-3-app-a
spec:
  podSelector:
    matchLabels:
      app: tier-3-app-a
  port: 8080
  proxyProtocol: HTTP/2